### PR TITLE
[N/A] Updates to testbed app

### PR DESCRIPTION
**Pull request by pjbroadbent**
Miscellaneous updates to the testbed app, based on feedback and further testing:
- Testbed now implements Save & Restore API calls
- Added window position to 'spawn' utils
- Client API now attached to window (as `Layouts`) for easier debugging/testing
- Added all app-applicable events to the event log UI
- Improved 'scroll to end' behaviour of the event log UI
- Toggling remove/close tab buttons to show when they are applicable, as with undock buttons
- Can toggle the filtering of the add tab/create tabgroup dropdowns, for better API edge-case testing

### CODE REVIEW

**Comment by tomrobertsOF** [comment]
LGTM!!!

**Comment by MichaelMCoates** [comment]
Looks great! Looks like my `wasCreatedProgrammatically` check wasn't thorough enough, can you please make it a bit more flexible? I made a quick update here, but I think it could be more robust: https://github.com/MichaelMCoates/layouts-service/blob/784a4f468a5573a1d0f2f71cd55f00da73c08ca9/src/provider/workspaces/utils.ts#L140

**Comment by MichaelMCoates** [comment]
Also don't forget to update the `Create Random App` buttons!

**Comment by pjbroadbent** [comment]
@MichaelMCoates Have added button fixes and updated the `wasCreatedProgrammatically` check

**Pull request merged**
